#ifndef ARRAYFIRE_TPCDI_ENUMS_H
#define ARRAYFIRE_TPCDI_ENUMS_H

enum DateFormat {
    YYYYMMDD,
    YYYYDDMM,
    DDMMYYYY,
    MMDDYYYY,
};

enum DataType { INT, SHORT, LONG, UINT, UCHAR, USHORT, ULONG, FLOAT, DOUBLE, STRING, BOOL, DATE, TIME, DATETIME };

#endif //ARRAYFIRE_TPCDI_ENUMS_H
